quetzal19/dkc-kz-aggregation

backend/config/packages/doctrine_mongodb.yaml
backend/src/Command/TestProductImportCommand.php
backend/src/Controller/ProductsController.php
backend/src/Document/Product.php
backend/src/Enum/SortOrder.php
backend/src/Enum/SortType.php
backend/src/MessageHandler/ProductImportHandler.php
backend/src/Repository/ProductRepository.php
backend/src/Service/ProductListService.php

https://track.ratio.digital/youtrack/issue/DKCKZ-357

DKCKZ-357 Фильтры. Список товаров

---

backend/composer.json
backend/composer.lock
backend/config/bundles.php
backend/config/packages/monolog.yaml
backend/config/services.yaml
backend/src/Command/ProcessingDataFromTempStorageCommand.php
backend/src/Command/Test/Queue/TestFillingQueueByFiles.php
backend/src/Command/Test/TestCreateTempStorageCommand.php
backend/src/Command/Test/TestGetMaxPriorityDataCommand.php
backend/src/Document/Section/Section.php
backend/src/Features/Priority/Builder/PriorityFilterBuilder.php
backend/src/Features/Section/DTO/Message/SectionMessageDTO.php
backend/src/Features/Section/Handler/SectionHandlerStorage.php
backend/src/Features/Section/Mapper/SectionMapper.php
backend/src/Features/Section/Repository/SectionRepository.php
backend/src/Features/Section/Service/SectionActionService.php
backend/src/Features/Section/Service/SectionValidatorService.php
backend/src/Features/TempStorage/Handler/Queue/TempStorageQueueHandler.php
backend/src/Features/TempStorage/Mapper/TempStorageMapper.php
backend/src/Features/TempStorage/Service/TempStorageValidatorService.php
backend/src/Helper/Enum/LocaleType.php
backend/src/Helper/Interface/ActionInterface.php
backend/src/Helper/Interface/EntityHandlerStorageInterface.php
backend/src/Helper/Interface/Mapper/MapperInterface.php
backend/src/Helper/Interface/Mapper/MapperMessageInterface.php
backend/src/Helper/Locator/Storage/ServiceHandlerStorageLocator.php
backend/symfony.lock

- описан обработчик временного хранилища
- описан обработчик для сущности раздела
- описан сервис валидации для сущности раздела
- описан сервис действий для сущности раздела 
- описан DTO для сущности раздела
- добавлен monolog для логирования
https://track.ratio.digital/youtrack/issue/DKCKZ-411

DKCKZ-411 Сохранение данных по Разделам. Фильтры. Список товаров

---

backend/config/packages/priority.yaml
backend/config/services.yaml
backend/src/Document/Product/Product.php
backend/src/Document/Properties/Name/PropertyName.php
backend/src/Document/Properties/Property.php
backend/src/Document/Properties/PropertyValue.php
backend/src/Document/Properties/Unit/PropertyUnit.php
backend/src/Features/Product/Mapper/ProductMapper.php
backend/src/Features/Property/DTO/Message/PropertyMessageDTO.php
backend/src/Features/Property/Handler/PropertyHandlerStorage.php
backend/src/Features/Property/Repository/PropertyRepository.php
backend/src/Features/Property/Service/PropertyActionService.php
backend/src/Features/PropertyUnit/DTO/Message/PropertyUnitMessageDTO.php
backend/src/Features/PropertyUnit/Handler/PropertyUnitHandlerStorage.php
backend/src/Features/PropertyUnit/Service/PropertyUnitActionService.php
backend/src/Features/PropertyValue/DTO/Message/PropertyValueMessageDTO.php
backend/src/Features/PropertyValue/Handler/PropertyValueHandlerStorage.php
backend/src/Features/PropertyValue/Repository/PropertyValueRepository.php
backend/src/Features/PropertyValue/Service/PropertyValueActionService.php
backend/src/Helper/Abstract/AbstractEntityHandlerStorage.php

- добавлен обработчик, property, propertyValue, propertyUnit
- добавлен без реализации сервис действий для документов
- добавлен DTO для документов property
https://track.ratio.digital/youtrack/issue/DKCKZ-413

DKCKZ-413 Исследование вариантов обработки данных. Фильтры. Список товаров

---

backend/src/Document/Product/Product.php

- добавлено поле property, для документа Product
https://track.ratio.digital/youtrack/issue/DKCKZ-418

DKCKZ-418 Добавить в документ Product параметр property. Фильтры. Список товаров

---

backend/config/services.yaml
backend/src/Command/Test/Queue/TestFillingQueueByFiles.php
backend/src/Document/Properties/Name/PropertyName.php
backend/src/Features/Message/Service/MessageService.php
backend/src/Features/Property/DTO/Message/PropertyMessageDTO.php
backend/src/Features/Property/DTO/Message/PropertyNameMessageDTO.php
backend/src/Features/Property/Mapper/PropertyMapper.php
backend/src/Features/Property/Mapper/PropertyNameMapper.php
backend/src/Features/Property/Serializer/Denormalizer/PropertyMessageDTODenormalizer.php
backend/src/Features/Property/Service/PropertyActionService.php

- добавлена реализация обработчика property
- добавлен DTO, mapper, для property и для поддокумента propertyName
- добавлен денормалайзер для propertyDTO
https://track.ratio.digital/youtrack/issue/DKCKZ-419

DKCKZ-419 Описать документ Property + сохранение данных. Фильтры. Список товаров

---

backend/config/services.yaml
backend/src/Document/Product/Product.php
backend/src/Document/Properties/PropertyValue.php
backend/src/Features/Priority/Builder/PriorityFilterBuilder.php
backend/src/Features/ProductFeature/DTO/Message/ProductFeatureMessageDTO.php
backend/src/Features/ProductFeature/DTO/Message/ProductFeaturePrimaryKeyDTO.php
backend/src/Features/ProductFeature/Handler/ProductFeatureHandlerStorage.php
backend/src/Features/ProductFeature/Serializer/Denormalizer/ProductFeatureMessageDTODenormalizer.php
backend/src/Features/ProductFeature/Service/ProductFeatureActionService.php
backend/src/Features/Properties/PropertyValue/Builder/Message/PropertyValueMessageDTOBuilder.php
backend/src/Features/Section/DTO/Message/SectionMessageDTO.php
backend/src/Helper/Interface/BuilderInterface.php

- добавлена реализация обработчика product features
- добавлен денормалайзер, builder для DTO
https://track.ratio.digital/youtrack/issue/DKCKZ-421

DKCKZ-421 Обработка product_features. Фильтры. Список товаров

---

backend/config/services.yaml
backend/src/Command/Test/Queue/TestFillingQueueByFiles.php
backend/src/Document/Product/Product.php
backend/src/Document/Properties/Property.php
backend/src/Features/ProductFeature/DTO/Message/ProductFeatureMessageDTO.php
backend/src/Features/Properties/PropertyFeatureMap/DTO/Message/PropertyFeatureMapMessageDTO.php
backend/src/Features/Properties/PropertyFeatureMap/DTO/Message/PropertyFeatureMapPrimaryKeyDTO.php
backend/src/Features/Properties/PropertyFeatureMap/Handler/PropertyFeatureMapHandlerStorage.php
backend/src/Features/Properties/PropertyFeatureMap/Serializer/Denormalizer/PropertyFeatureMapMessageDTODenormalizer.php
backend/src/Features/Properties/PropertyFeatureMap/Service/PropertyFeatureMapActionService.php

- реализация обработчика etim_art_class_feature_map
- добавлен DTO, denoramlizer для обработки
- изменена тестовая команда для заполнения очереди
- изменена реализаця назначения property у документа Product
https://track.ratio.digital/youtrack/issue/DKCKZ-422

DKCKZ-422 Обработка etim_art_class_feature_map. Фильтры. Список товаров

---

backend/config/services.yaml
backend/src/Command/ProcessingDataFromTempStorageCommand.php
backend/src/Features/Priority/Service/PriorityService.php
backend/src/Features/Product/Service/ProductActionService.php
backend/src/Features/ProductFeature/Service/ProductFeatureActionService.php
backend/src/Features/Properties/Property/Service/PropertyActionService.php
backend/src/Features/Properties/PropertyFeatureMap/Service/PropertyFeatureMapActionService.php
backend/src/Features/Properties/PropertyUnit/DTO/Message/PropertyUnitMessageDTO.php
backend/src/Features/Properties/PropertyUnit/Serializer/Denormalizer/PropertyUnitMessageDTODenormalizer.php
backend/src/Features/Properties/PropertyUnit/Service/PropertyUnitActionService.php
backend/src/Features/Properties/PropertyValue/Service/PropertyValueActionService.php
backend/src/Features/Section/Service/SectionActionService.php
backend/src/Helper/Abstract/AbstractEntityHandlerStorage.php
backend/src/Helper/Interface/ActionInterface.php
backend/src/Helper/Interface/EntityHandlerStorageInterface.php

- добавлено DTO, денормалайзер
- реализация обработчика etim_unit
- изменен тип возвращаемого значения на bool  в actionInterface, в сервисах, где реализован интерфейс
- изменена команда обработки временного хранилища, добавлено условие для etimUnitHandlerStorage
https://track.ratio.digital/youtrack/issue/DKCKZ-423

DKCKZ-423 Обработка etim_unit.  Фильтры. Список товаров

---

backend/composer.json
backend/config/services.yaml
backend/src/Document/Properties/Property.php
backend/src/Document/Properties/SectionCode/SectionCode.php
backend/src/Document/Section/Section.php
backend/src/Features/Properties/Property/Repository/PropertyRepository.php
backend/src/Features/Section/Repository/SectionRepository.php
backend/src/Features/SectionFeature/DTO/Message/SectionFeatureMessageDTO.php
backend/src/Features/SectionFeature/DTO/Message/SectionFeaturePrimaryKeyDTO.php
backend/src/Features/SectionFeature/Handler/SectionFeatureHandlerStorage.php
backend/src/Features/SectionFeature/Serializer/Denormalizer/SectionFeatureMessageDTODenormalizer.php
backend/src/Features/SectionFeature/Service/SectionFeatureActionService.php

- реализация обработчика facet_feature_section
- добавлен DTO, denormalizer, action сервис
- изменен метод репозитория раздела для поиска подразделов
- добавлен в репозиторий property метод для поиска по разделам вместе с сортировкой
https://track.ratio.digital/youtrack/issue/DKCKZ-425

DKCKZ-425 Обработка facet_feature_section. Фильтры. Список товаров

---

backend/composer.json
backend/composer.lock
backend/config/bundles.php
backend/config/packages/nelmio_api_doc.yaml
backend/config/routes.yaml
backend/config/routes/nelmio_api_doc.yaml
backend/src/Controller/Api/v1/AccessoryController.php
backend/src/Controller/Api/v1/AnalogController.php
backend/src/Document/Analog/Analog.php
backend/src/Features/Accessory/Filter/AccessoryFilter.php
backend/src/Features/Accessory/Repository/AccessoryRepository.php
backend/src/Features/Accessory/Service/AccessoryService.php
backend/src/Features/Analog/Filter/AnalogFilter.php
backend/src/Features/Analog/Repository/AnalogRepository.php
backend/src/Features/Analog/Service/AnalogService.php
backend/src/Features/Product/Repository/ProductRepository.php
backend/src/Features/Section/Repository/SectionRepository.php
backend/src/Helper/Abstract/AbstractSectionService.php
backend/src/Helper/Abstract/AbstractSectionServiceDocumentRepository.php
backend/src/Helper/DTO/Data/Product/AnalogAccessoryProductDTO.php
backend/src/Helper/DTO/Data/Product/AnalogAccessoryProductDataDTO.php
backend/src/Helper/DTO/Data/Product/AnalogAccessoryProductItemDTO.php
backend/src/Helper/DTO/Data/Section/AnalogAccessorySectionDTO.php
backend/src/Helper/DTO/Data/Section/AnalogAccessorySectionDataDTO.php
backend/src/Helper/DTO/Data/Section/AnalogAccessorySectionItemDTO.php
backend/src/Helper/Exception/Attributes/NotFoundResponse.php
backend/src/Helper/Exception/Attributes/NotValidDataResponse.php
backend/src/Helper/Validator/ValidatorService.php
backend/symfony.lock

- добавлен метод получения списка разделов аналогов/аксессуаров
- добавлен метод получения списка аналогов/аксессуаров
- добавлено документация API
https://track.ratio.digital/youtrack/issue/DKCKZ-435

DKCKZ-435 Методы API. Аналоги и аксессуары. Детальная страница товара

---

Makefile
docker/.gitignore
docker/dev/cron/Dockerfile
docker/dev/mongo/initdb.d/create-app-user.sh
docker/dev/mongo/initdb.d/mongo-init.js
docker/dev/nginx/default.conf
docker/dev/php/Dockerfile
docker/dev/php/conf.d/error_reporting.ini
docker/dev/php/conf.d/php.ini
docker/docker-compose.dev.yml

https://track.ratio.digital/youtrack/issue/DKCKZ-342

DKCKZ-342 Описание сборки docker-compose для dev окружения

---

crontab
docker/dev/nginx/default.conf
docker/docker-compose.dev.yml

DKCKZ-441 Доработки для запуска сервиса

---

Makefile

https://track.ratio.digital/youtrack/issue/DKCKZ-342

DKCKZ-342 Правки в Makefile

---

Makefile
backend/config/packages/messenger.yaml
backend/src/Command/Test/Queue/TestFillingQueueByFiles.php
backend/src/Features/TempStorage/DTO/Message/TempStorageMessage.php
backend/src/Features/TempStorage/Handler/Queue/TempStorageQueueHandler.php
backend/src/Features/TempStorage/Serializer/TempStorageMessageSerializer.php

- добавлен сериалайзер для json, для обработки сообщений в очереди
- добавлена прослойка DTO для обработки в DTO временного хранилища
- изменен сериалайзер у обработчика очередей
https://track.ratio.digital/youtrack/issue/DKCKZ-447

DKCKZ-447 Изменение типа сообщения в очереди. Аналоги и аксессуары. Детальная страница товара

---

crontab
docker/.gitignore

DKCKZ-441 Поправлен список задач для cron, дополнен docker/.gitignore

---

backend/src/Command/ProcessingDataFromTempStorageCommand.php
backend/src/Document/Properties/PropertyValue.php
backend/src/Document/Storage/Temp/TempStorage.php
backend/src/Features/Accessory/Service/AccessoryActionService.php
backend/src/Features/Analog/Service/AnalogActionService.php
backend/src/Features/Message/Service/MessageService.php
backend/src/Features/Priority/Service/PriorityService.php
backend/src/Features/Product/DTO/Message/ProductMessageDTO.php
backend/src/Features/Product/Service/ProductActionService.php
backend/src/Features/ProductFeature/Service/ProductFeatureActionService.php
backend/src/Features/Properties/Property/Service/PropertyActionService.php
backend/src/Features/Properties/PropertyFeatureMap/Service/PropertyFeatureMapActionService.php
backend/src/Features/Properties/PropertyUnit/Service/PropertyUnitActionService.php
backend/src/Features/Properties/PropertyValue/Service/PropertyValueActionService.php
backend/src/Features/Section/DTO/Message/SectionMessageDTO.php
backend/src/Features/Section/Service/SectionActionService.php
backend/src/Features/SectionFeature/Service/SectionFeatureActionService.php
backend/src/Features/TempStorage/Repository/TempStorageRepository.php
backend/src/Helper/Abstract/AbstractEntityHandlerStorage.php
backend/src/Helper/Interface/EntityHandlerStorageInterface.php

- оптимизация команды по обработке очереди временного хранилища
- добавлен аргумент к команде обработке временного хранилища
- изменена логика временного хранилища, удаление TempStorage при успешной обработке
- изменена логика действия update
- выполнить `php bin/console doctrine:mongodb:schema:update` для обновления индексов
https://track.ratio.digital/youtrack/issue/DKCKZ-449

DKCKZ-449 Оптимизация обработки данных из TempStorage. Аналоги и аксессуары. Детальная страница товара

---

backend/src/Features/Accessory/Repository/AccessoryRepository.php
backend/src/Features/Accessory/Service/AccessoryService.php
backend/src/Features/Analog/Repository/AnalogRepository.php
backend/src/Features/Analog/Service/AnalogService.php
backend/src/Helper/Abstract/AbstractSectionService.php
backend/src/Helper/Abstract/AbstractSectionServiceDocumentRepository.php
crontab

- оптимизация запросов Аксессуаров и Аналогов

DKCKZ-441 Оптимизация запросов Аксессуаров и Аналогов

---

backend/src/Features/Accessory/Service/AccessoryService.php
backend/src/Features/Analog/Service/AnalogService.php
backend/src/Helper/Abstract/AbstractSectionServiceDocumentRepository.php

DKCKZ-441 Оптимизация запросов разделов аналогов и аксессуаров

---

backend/src/Helper/Abstract/AbstractSectionServiceDocumentRepository.php

- Исправлена выдача категорий в аналогах и аксессуарах, теперь для определения списка категорий учитывается наличие у категории товара выбранной локали

DKCKZ-441 Исправлена выдача категорий в аналогах и аксессуарах

---

backend/src/Features/Accessory/Repository/AccessoryRepository.php
backend/src/Features/Accessory/Service/AccessoryService.php
backend/src/Features/Analog/Repository/AnalogRepository.php
backend/src/Features/Analog/Service/AnalogService.php
backend/src/Helper/Abstract/AbstractSectionServiceDocumentRepository.php

DKCKZ-441 Доработано получение категорий в аналогах и аксессуарах

---

backend/src/Document/Product/Product.php
backend/src/Features/Product/DTO/Message/ProductMessageDTO.php

- Объем и Вес могут быть не указаны для товара.

DKCKZ-441 Доработана валидация параметров Товара

---

backend/src/Features/TempStorage/Repository/TempStorageRepository.php

https://track.ratio.digital/youtrack/issue/DKCKZ-451

DKCKZ-451 Поправлена сортировка при выборке пакетов с данными

---

docker/.gitignore
docker/docker-compose.stage.yml
docker/stage/cron/Dockerfile
docker/stage/mongo/initdb.d/create-app-user.sh
docker/stage/mongo/initdb.d/mongo-init.js
docker/stage/nginx/default.conf
docker/stage/php/Dockerfile
docker/stage/php/conf.d/error_reporting.ini
docker/stage/php/conf.d/php.ini

https://track.ratio.digital/youtrack/issue/DKCKZ-458

DKCKZ-458 Добавлено описание для окружения stage

---

docker/stage/nginx/default.conf

https://track.ratio.digital/youtrack/issue/DKCKZ-458

DKCKZ-458: Скорректирована конфигурация nginx для stage окружения

---

backend/config/packages/monolog.yaml

https://track.ratio.digital/youtrack/issue/DKCKZ-458

DKCKZ-458 Настроено логирование для prod окружения

---

backend/src/Helper/Abstract/AbstractAnalogAccessoryRepository.php

https://track.ratio.digital/youtrack/issue/DKCKZ-459

DKCKZ-459 Исправлена выборка аналогов и аксессуаров

---

docker/.gitignore
docker/docker-compose.prod.yml
docker/prod/cron/Dockerfile
docker/prod/mongo/initdb.d/create-app-user.sh
docker/prod/mongo/initdb.d/mongo-init.js
docker/prod/nginx/default.conf
docker/prod/php/Dockerfile
docker/prod/php/conf.d/error_reporting.ini
docker/prod/php/conf.d/php.ini

https://track.ratio.digital/youtrack/issue/DKCKZ-458

DKCKZ-458 Описание для окружения prod

---

backend/src/Command/ProcessingDataFromTempStorageCommand.php
backend/src/Command/Test/Queue/TestAddTempStorage.php
backend/src/Document/Accessory/Accessory.php
backend/src/Document/Analog/Analog.php
crontab

- обновлены задания на кроне
- обновлены индексы в Аксессуарах
- индекс externalId теперь уникальный
- добавлены уникальный составной индекс element - accessory
- обновлены индексы в Аналогах
- индекс externalId теперь уникальный
- добавлены уникальный составной индекс element - analog
- добавлена обработка исключения при ошибке связанной с индексами
- добавлена тестовая команда, которая добавляет сообщение в очередь
- выполнить в консоли `php bin/console doctrine:mongodb:schema:update` (если нужно, почистить Аналоги и Аксессуары)

DKCKZ-464 Добавлены уникальные индексы для Аналогов и Аксессуаров

---

backend/src/Features/Accessory/Service/AccessoryActionService.php
backend/src/Features/Analog/Service/AnalogActionService.php
backend/src/Features/TempStorage/Error/Type/ErrorType.php

Добавлена дополнительная проверка наличия дубликата связки товар - аналог или аксессуар
https://track.ratio.digital/youtrack/issue/DKCKZ-471

DKCKZ-471 Доработан процесс сохранения Аналога или Аксессуара
